### Health route checks server and DB connection
GET http://localhost:3000/health


### USERS

### List all users
GET http://localhost:3000/users

### Create User
POST http://localhost:3000/users/
Content-Type: application/json

{
  "name": "Ender",
  "email": "ender@example.com",
  "password": "hashedpassword123"
}

### Login User
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "name": "Andrew",
  "password": "hashedpassword1234"
}

### Update User
PUT http://localhost:3000/users
Content-Type: application/json

{
  "name": "Andrew",
  "password": "hashedpassword1234"
}

### Delete User
DELETE http://localhost:3000/users/

### POSTS

### List all posts
GET http://localhost:3000/posts

### COMMENTS

### List all comments
GET http://localhost:3000/comments

### LIKES

### List all likes
GET http://localhost:3000/likes